---
# CIS 6 - Special Purpose Services
# 6.1 Ensure the X Window system is not installed
  - name: Special Services - xserver absent
    apt: pkg=xserver-xorg-* state=absent
    when: "'users' not in group_names"
# 6.2 Ensure Avahi Server is not enabled
  - name: Special Services - avahi absent
    apt: pkg=avahi-daemon state=absent
# 6.3 Ensure print server is not enabled
  - name: Special Services - cups absent
    apt: pkg=cups-* state=absent
    when: "'users' not in group_names"
# 6.4 Ensure DHCP Server is not enabled
  - name: Special Services - DHCP server absent
    apt: pkg=isc-dhcp-server state=absent
# 6.5 Configure Network Time Protocol (NTP)
# 6.6 Ensure LDAP is not enabled
  - name: Special Services - LDAP absent
    apt: pkg=slapd state=absent
# 6.7 Ensure NFS and RPC are not enabled
  - name: Special Services - NFS server absent
    apt: pkg=nfs-kernel-server state=absent
  - name: Special Services - RPC server absent
    apt: pkg=rpcbind state=absent
# 6.8 Ensure DNS Server is not enabled
  - name: Special Services - DNS server absent
    apt: pkg=bind9 state=absent
# 6.9 Ensure FTP Server is not enabled
# 6.10 Ensure HTTP Server is not enabled
# 6.11 Ensure IMAP and POP server is not enabled
  - name: Special Services - IMAP server absent dovecot
    apt: pkg=dovecot-* state=absent
  - name: Special Services - IMAP server absent courier
    apt: pkg=courier-* state=absent
# 6.12 Ensure Samba is not enabled
  - name: Special Services - Samba server absent
    apt: pkg=samba state=absent
# 6.13 Ensure HTTP Proxy Server is not enabled
# 6.14 Ensure SNMP Server is not enabled
  - name: Special Services - SNMP server absent
    apt: pkg=snmpd state=absent
# 6.15 Configure Mail Transfer Agent for Local-Only Mode
  - name: Special Services - SMTP email to mailrelay
    apt: pkg=postfix state=present
  - name: Special Services - SMTP hardening - banner
    lineinfile: dest=/etc/postfix/main.cf
                regexp='^smtpd_banner'
                line='smtpd_banner = $myhostname ESMTP'
                state=present
    notify: Restart postfix
  - name: Special Services - SMTP hardening - local only
    lineinfile: dest=/etc/postfix/main.cf
                regexp='inet_interfaces'
                line='inet_interfaces = localhost'
                state=present
    notify: Restart postfix
  - name: Special Services - SMTP hardening - mynetwork
    lineinfile: dest=/etc/postfix/main.cf
                regexp='^mynetworks'
                line='mynetworks = 127.0.0.0/8'
                state=present
# 6.17 Ensure Biosdevname is enabled
  - name: Special Services - Biosdevname is enabled
    apt: pkg=biosdevname state=latest
