---
# CIS 7 - Network Configuration and Firewalls
# 7.1 Modify Network Parameters (Host Only)
# 7.1.1 Disable IP Forwarding
  - name: Network - Disable IP Forwarding v4
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.ip_forward'
                line='net.ipv4.ip_forward = 0'
                state=present
    notify: Restart sysctl
    when: is_a_router == "no"
  - name: Network - Disable IP Forwarding v6
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.all.forwarding'
                line='net.ipv6.conf.all.forwarding = 0'
                state=present
    notify: Restart sysctl
# 7.1.2 Disable Send Packet Redirects
  - name: Network - Disable Send Packet Redirects (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.send_redirects'
                line='net.ipv4.conf.all.send_redirects = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable Send Packet Redirects (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.send_redirects'
                line='net.ipv4.conf.default.send_redirects = 0'
                state=present
    notify: Restart sysctl
# 7.2 Modify Network Parameters (Host and Router)
# 7.2.1 Disable Source Routed Packet Acceptance
  - name: Network - Disable Source Routed Packet Acceptance (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.accept_source_route'
                line='net.ipv4.conf.all.accept_source_route = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable Source Routed Packet Acceptance (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.accept_source_route'
                line='net.ipv4.conf.default.accept_source_route = 0'
                state=present
    notify: Restart sysctl
# 7.2.2 Disable ICMP Redirect Acceptance
  - name: Network - Disable ICMP Redirect Acceptance (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.accept_redirects'
                line='net.ipv4.conf.all.accept_redirects = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable ICMP Redirect Acceptance (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.accept_redirects'
                line='net.ipv4.conf.default.accept_redirects = 0'
                state=present
    notify: Restart sysctl
# 7.2.3 Disable Secure ICMP Redirect Acceptance
  - name: Network - Disable Secure ICMP Redirect Acceptance (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.secure_redirects'
                line='net.ipv4.conf.all.secure_redirects = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable Secure ICMP Redirect Acceptance (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.secure_redirects'
                line='net.ipv4.conf.default.secure_redirects = 0'
                state=present
    notify: Restart sysctl
# 7.2.4 Log Suspicious Packets
  - name: Network - Log Suspicious Packets (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.log_martians'
                line='net.ipv4.conf.all.log_martians = 1'
                state=present
    notify: Restart sysctl
  - name: Network - Log Suspicious Packets (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.log_martians'
                line='net.ipv4.conf.default.log_martians = 1'
                state=present
    notify: Restart sysctl
# 7.2.5 Enable Ignore Broadcast Requests
  - name: Network - Enable Ignore Broadcast Requests
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.icmp_echo_ignore_broadcasts'
                line='net.ipv4.icmp_echo_ignore_broadcasts = 1'
                state=present
    notify: Restart sysctl
# 7.2.6 Enable Bad Error Message Protection
  - name: Network - Enable Bad Error Message Protection
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.icmp_ignore_bogus_error_responses'
                line='net.ipv4.icmp_ignore_bogus_error_responses = 1'
                state=present
    notify: Restart sysctl
# 7.2.7 Enable RFC-recommended Source Route Validation
  - name: Network - Enable RFC-recommended Source Route Validation (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.all.rp_filter'
                line='net.ipv4.conf.all.rp_filter = 1'
                state=present
    notify: Restart sysctl
  - name: Network - Enable RFC-recommended Source Route Validation (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.conf.default.rp_filter'
                line='net.ipv4.conf.default.rp_filter = 1'
                state=present
    notify: Restart sysctl
# 7.2.8 Enable TCP SYN Cookies
  - name: Network - Enable TCP SYN Cookies
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv4.tcp_syncookies'
                line='net.ipv4.tcp_syncookies = 1'
                state=present
    notify: Restart sysctl
# 7.3 Configure IPv6
# 7.3.1 Disable IPv6 Router Advertisements
  - name: Network - Disable IPv6 Router Advertisements (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.all.accept_ra'
                line='net.ipv6.conf.all.accept_ra = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable IPv6 Router Advertisements (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.default.accept_ra'
                line='net.ipv6.conf.default.accept_ra = 0'
                state=present
    notify: Restart sysctl
# 7.3.2 Disable IPv6 Redirect Acceptance
  - name: Network - Disable IPv6 Redirect Acceptance (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.all.accept_redirects'
                line='net.ipv6.conf.all.accept_redirects = 0'
                state=present
    notify: Restart sysctl
  - name: Network - Disable IPv6 Redirect Acceptance (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.default.accept_redirects'
                line='net.ipv6.conf.default.accept_redirects = 0'
                state=present
    notify: Restart sysctl
# 7.3.3 Disable IPv6
  - name: Network - Disable IPv6 (all)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.all.disable_ipv6'
                line='net.ipv6.conf.all.disable_ipv6 = 1'
                state=present
    notify: Restart sysctl
  - name: Network - Disable IPv6 (default)
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.default.disable_ipv6'
                line='net.ipv6.conf.default.disable_ipv6 = 1'
                state=present
    notify: Restart sysctl
  - name: Network - Disable IPv6
    lineinfile: dest=/etc/sysctl.conf
                regexp='net.ipv6.conf.lo.disable_ipv6'
                line='net.ipv6.conf.lo.disable_ipv6 = 1'
                state=present
    notify: Restart sysctl
  - name: Network - Disable IPv6 - remove refs in /etc/hosts
    lineinfile: dest=/etc/hosts
                regexp='::'
                state=absent
# 7.4 Install TCP Wrappers
# 7.4.1 Install TCP Wrappers
  - name: Network - tcpwrapper installed
    apt: pkg=tcpd state=present
# 7.4.2 Create /etc/hosts.allow
  - name: Network - hosts.allow exists and is strict
    lineinfile: "dest=/etc/hosts.allow regexp='ALL:' line='ALL: {{ physical_host }}' state=present create=yes"
# 7.4.3 Verify Permissions on /etc/hosts.allow
  - name: Network - hosts.allow has correct permissions
    file: dest=/etc/hosts.allow
          mode=0644
          owner=root
          group=root
# 7.4.4 Create /etc/hosts.deny
  - name: Network - hosts.deny exists and is strict
    lineinfile: "dest=/etc/hosts.deny regexp='ALL:' line='ALL: ALL' state=present create=yes"
# 7.4.5 Verify Permissions on /etc/hosts.deny
  - name: Network - hosts.deny has correct permissions
    file: dest=/etc/hosts.deny
          mode=0644
          owner=root
          group=root
# 7.5 Uncommon Network Protocols
# 7.5.1 Disable DCCP
  - name: DCCP kernel module blacklist
    lineinfile: dest=/etc/modprobe.d/blacklist-baseline.conf
                regexp='dccp$'
                line='blacklist dccp'
                state=present
                create=yes
  - name: DCCP_CCID2 kernel module blacklist
    lineinfile: dest=/etc/modprobe.d/blacklist-baseline.conf
                regexp='dccp_ccid2'
                line='blacklist dccp_ccid2'
                state=present
  - name: DCCP_CCID3 kernel module blacklist
    lineinfile: dest=/etc/modprobe.d/blacklist-baseline.conf
                regexp='dccp_ccid3'
                line='blacklist dccp_ccid3'
                state=present
# 7.5.2 Disable SCTP
# 7.5.3 Disable RDS
# 7.5.4 Disable TIPC
# 7.6 Deactivate Wireless Interfaces
# 7.7 Ensure Firewall is active
  - name: Network - Firewall is installed
    apt: pkg=ufw state=present
  - name: Network - Firewall DEFAULT_INPUT_POLICY
    lineinfile: dest=/etc/default/ufw
                regexp='^DEFAULT_INPUT_POLICY'
                line='DEFAULT_INPUT_POLICY="DROP"'
                state=present
  - name: Network - Firewall DEFAULT_OUTPUT_POLICY
    lineinfile: dest=/etc/default/ufw
                regexp='^DEFAULT_OUTPUT_POLICY'
                line='DEFAULT_OUTPUT_POLICY="ACCEPT"'
                state=present
  - name: Network - Firewall DEFAULT_FORWARD_POLICY
    lineinfile: dest=/etc/default/ufw
                regexp='^DEFAULT_FORWARD_POLICY'
                line='DEFAULT_FORWARD_POLICY="DROP"'
                state=present
  - name: Network - Firewall DEFAULT_APPLICATION_POLICY
    lineinfile: dest=/etc/default/ufw
                regexp='^DEFAULT_APPLICATION_POLICY'
                line='DEFAULT_APPLICATION_POLICY="SKIP"'
                state=present
  - name: Network - Firewall allow SSH
    shell: ufw allow {{ item }}
    with_items:
      - OpenSSH
      - ssh
  - name: Network - Firewall is enabled at boot (ufw.conf)
    lineinfile: dest=/etc/ufw/ufw.conf
                regexp='^ENABLED'
                line='ENABLED=yes'
                state=present
    notify: Restart ufw
